#!/bin/sh -e

if [ -d 'dist' ] ; then
    rm -r dist
fi
if [ -d 'site' ] ; then
    rm -r site
fi
if [ -d 'pyidoit.egg-info' ] ; then
    rm -r pyidoit.egg-info
fi

find pyidoit -type f -name "*.py[co]" -delete
find pyidoit -type d -name __pycache__ -delete